src/pages/AlterarSenha/AlterarSenha.js, src/pages/AlterarSenha/Styles.js, src/pages/EditarPerfil/EditarPerfil.js, src/pages/EditarPerfil/Styles.js, src/pages/PerfilPaciente/PerfilPaciente.js, src/pages/PerfilPaciente/Styles.js
Responsividade botões de alterar senha e responsividade do espaçamento dos inputs
=> Revisão responsividade 

src/services/ManagerService/managerService.js, src/services/RequesterService/requesterService.js
Arrumando bug que todos os usuários estavam renderizando todos os agendamentos no Modal Agendamento. Agora cada usuário está renderizando apenas os agendamentos que foram designados a ele. 
O problema era que estava puxando a função errada do manager
=> Todos os usuários estavam renderizando todos os agendamentos 

src/components/ModalAgendamento/ModalAgendamento.js, src/components/ModalAgendamento/Styles.js
Duracao no modal agendamento e responsividade
=> Duracao no modal agendamento

src/pages/EditarPerfil/EditarPerfil.js, src/pages/EditarPerfil/Styles.js, src/pages/Perfil/Perfil.js, src/pages/Perfil/Styles.js, src/pages/PerfilPaciente/PerfilPaciente.js, src/pages/PerfilPaciente/Styles.js, src/styles/Button/Button.js
Adicionei campos "Convênio", "Cuidador" e "Telefone do Cuidador" na página PerfilPaciente, com esses campos NÃO renderizando apenas nos perfis de secretário(a) ;
Adicionei títulos (Pais, Estado, Cidade…) nas informações do PerfilPessoal;
Adicionei títulos (Nome, País, Telefone...) nos inputs da página EditarPerfil;
Alterei a responsividade nas páginas: PerfilPaciente, PerfilPessoal e EditarPerfil;
=> Novos campos e rótulos Perfil Pessoal, Paciente e Editar Perfil

src/components/ModalAgendamento/ModalAgendamento.js, src/components/ModalAgendamentoEspecifico/ModalAgendamentoEspecifico.js, src/components/ModalEditarAgendamentoEspecifico/ModalEditarAgendamentoEspecifico.js, src/components/ModalEditarAgendamentoEspecifico/Styles.js, src/components/ModalEditarAgendamentoEspecifico/index.js, src/services/ManagerService/managerService.js, src/services/RequesterService/requesterService.js, src/utils/masks.js
Ao atualizar os dados da consulta, o modal fecha e a página carrega automaticamente com os novos dados. Além disso, a escrita de texto no input de duração é bloqueada.
=> Editar Agendamento Funcional

src/components/ModalAdicionarCodigo/ModalAdicionarCodigo.js, src/pages/ListaUsuarios/ListaUsuarios.js, src/services/ManagerService/managerService.js
Possibilita ao médico adicionar e editar códigos de pacientes. Além disso o modal Adicionar Código fecha ao clicar no "x" ou fora dele
=>  Revisões Modal Adicionar Código e possibilitar alterar código Lista de Usuários

src/components/ModalAgendamentoEspecifico/ModalAgendamentoEspecifico.js, src/pages/Agendamentos/Agendamentos.js, src/pages/Agendamentos/Styles.js, src/services/ManagerService/managerService.js
Mostrar os códigos dos pacientes na página Agendamentos nas cores corretas
Clicar no paciente na página Agendamentos e redirecionar para o PerfilPaciente
No modal Agendamento Específico, adicionar um addToast quando a consulta for criada
=> Acessar perfil usuário e mostrar código Página Agendamentos

src/pages/PerfilPaciente/PerfilPaciente.js, src/pages/PerfilPaciente/Styles.js
Alteração responsiva das estrelas, alterar para renderizar em looping e mudar a cor do botão agendamentos.
=> Alterar estrelas perfil paciente

src/components/ModalAgendamentoEspecifico/ModalAgendamentoEspecifico.js, src/components/ModalAgendamentoEspecifico/Styles.js, src/pages/Cadastro/Cadastro.js, src/pages/Cadastro/Styles.js, src/styles/Select/Select.js, src/utils/date.js, src/utils/masks.js
Tratamento de Erros Implementado na pagina
=> TratamentoErroModalAgendamentoEspecifico

src/components/ModalAgendamentoEspecifico/ModalAgendamentoEspecifico.js, src/components/ModalEditarAgendamentoEspecifico/ModalEditarAgendamentoEspecifico.js, src/components/ModalEditarAgendamentoEspecifico/Styles.js
Adição de máscara para os campos data, horário e duração. Adição de rótulos e de uma mensagem de erro quando uma má requisição é feita.
=> Tratamento de Erros Modal Editar Agendamento

src/components/ModalAgendamento/ModalAgendamento.js, src/components/ModalAgendamento/Styles.js, src/pages/Agendamentos/Agendamentos.js, src/pages/Agendamentos/Styles.js, src/styles/Button/Button.js, src/utils/tratamentoErros.js
ordenação dos agendamentos por data e estilização da página de agendamentos
=> Alterar Design E Ordenação Agendamentos E Modal Agendamentos e Adição do arquvivo de Tratamento de Erros

src/pages/ListaUsuarios/ListaUsuarios.js
*Quando logado como médico, não queremos que apareça o Guilherme na lista de Usuários;
*Quando logado como médico, queremos que, na lista de usuários, APENAS os pacientes apareçam com a opção "editar código".
=> Retirar administrador e adicionar código secretária na Lista de Usuários

package.json, src/pages/CriacaoFormulario/CriacaoFormulario.js, src/pages/CriacaoFormulario/Styles.js, src/services/ManagerService/managerService.js, src/services/RequesterService/requesterService.js
Página criação formulários linkada com back e não estilizada 100%
=> Criação Formulários

src/components/ModalEditarFormulario/ModalEditarFormulario.js, src/components/ModalEditarFormulario/Styles.js, src/components/ModalEditarFormulario/index.js, src/pages/EditarFormulario/EditarFormulario.js, src/pages/EditarFormulario/Styles.js, src/pages/EditarFormulario/index.js, src/pages/ListaFormularios/ListaFormularios.js, src/routes.js, src/services/ManagerService/managerService.js, src/services/RequesterService/requesterService.js
Página editar formularios, modal de edicao e deletar formulario funcional
=> Editar formularios e deletar formulario

src/pages/Cadastro/Cadastro.js, src/pages/HomeMedico/HomeMedico.js, src/pages/HomeSecretaria/HomeSecretaria.js, src/pages/ListaUsuarios/ListaUsuarios.js, src/pages/ListaUsuarios/Styles.js, src/services/ManagerService/managerService.js, src/styles/Button/Button.js
Implementação de uma lógica para a renderização do select de tipo na página de cadastro. Ele só renderizará caso o usuário logado seja o médico e o acesso for feito pela url.
=> Passar Tipo De Usuário da Home Para o Cadastro

src/components/ModalAgendamentoEspecifico/ModalAgendamentoEspecifico.js, src/components/ModalAgendamentoEspecifico/Styles.js, src/components/ModalEditarAgendamentoEspecifico/ModalEditarAgendamentoEspecifico.js, src/pages/Agendamentos/Agendamentos.js, src/pages/PerfilPaciente/PerfilPaciente.js
Foi implementado tratamento de erro para data e horário anterior ao atual.
=> Dia e horário atual Modal Agendamento Específico

src/pages/Agendamentos/Agendamentos.js, src/pages/FormularioEspecifico/FormularioEspecifico.js, src/pages/FormularioEspecifico/Styles.js, src/pages/FormularioEspecifico/index.js, src/pages/ListaFormularios/ListaFormularios.js, src/pages/ListaUsuarios/Styles.js, src/routes.js, src/services/ManagerService/managerService.js, src/services/RequesterService/requesterService.js, src/styles/Button/Button.js, src/variaveis.js
Criação da página de formulário específico e sua rota, linkar o formulario especifico com a pagina lista formularios, criação da estilização da pagina (seu css), responsividade, puxar as infos do formulario especifico e os usuarios que possuem respostas pendentes ou que ja responderam, e lógica que calcula o numero de usuarios que responderam ou nao
=> Pagina Formulario Especifico

src/pages/ListaFormularios/ListaFormularios.js, src/pages/ListaFormularios/Styles.js
Responsividade dos botões enviar lembrete, editar e deletar, espaçamento entre eles, alterar cor das estrelas da urgencia (ordem estava trocada), função que renderiza os formularios de acordo com os filtros adicionados (urgencia tipo 1, 2, 3),, barra de busca por nome e titulo do forms e filtros apodendo atuar juntos.
=> Alterações e Filtro Lista formulários

package.json, src/components/Header/Header.js, src/pages/Cadastro/Cadastro.js, src/pages/ListaUsuarios/ListaUsuarios.js, src/pages/Login/Login.js, src/routes.js, src/services/ManagerService/managerService.js, yarn.lock
Retirar o botão de cadastre-se da página login, tornar rota cadastro privada, lógica para renderizar botão "voltar para login" apenas se não estiver logado, mudar redirecionamento para lista de usuários ao acessar o sistema e ao cadastrar novo usuario, tirar as rotas de home para não ser possivel acessar pela url e fazer com que ao digitar um url invalida redirecione para a lista de usuarios.
=> Direcionamento Home, usuário logado Login e Cadastro

package.json, src/components/ModalEditarFormulario/ModalEditarFormulario.js, src/components/ModalEditarFormulario/Styles.js, src/pages/EditarFormulario/EditarFormulario.js, src/pages/EditarFormulario/Styles.js, src/services/ManagerService/managerService.js, src/styles/Input/Input.js, src/styles/Select/Select.js, yarn.lock
Título nos inputs; tratar as opções do select da urgência para não repetir; loader no botão; campos nulos; responsividade; textos de orientação; mudança no layout;
=> Alterações editar formulários e modal editar formulários

src/components/ModalAgendamento/ModalAgendamento.js, src/components/ModalAgendamento/Styles.js, src/components/ModalConsultaMarcada/ModalConsultaMarcada.js, src/components/ModalConsultaMarcada/Styles.js, src/components/ModalConsultaMarcada/index.js, src/pages/Agendamentos/Agendamentos.js, src/pages/Agendamentos/Styles.js
Implementação de um modal com as informações da consulta para facilitar a visualização do usuário
=> Modal Consulta Marcada Funcional

src/pages/Cadastro/Cadastro.js, src/pages/ListaFormularios/ListaFormularios.js, src/pages/ListaUsuarios/ListaUsuarios.js, src/pages/ListaUsuarios/Styles.js, src/services/ManagerService/managerService.js, src/services/RequesterService/requesterService.js, yarn.lock
Trata responsividade para códigos de até 26 caracteres, ordena a lista de usuários por ordem alfabética e torna o campo última visita funcional
=> Última Visita e Código Lista de Usuários

src/components/Header/Header.js, src/pages/FormularioEspecifico/FormularioEspecifico.js, src/pages/FormularioEspecifico/Styles.js
Abre o modal de resposta do formulário ao clicar no nome do paciente na página de formulário específico
=> Resposta do Formulário Específico

src/pages/Cadastro/Cadastro.js, src/pages/EditarPerfil/EditarPerfil.js
Implementação do tipo data para a data de nascimento, de máscaras para número, país e cidade e estilização correta do Select.
=> Tratamento número e data Cadastro e Alterar Dados e input e-mail alterar dados

src/components/ModalExcluirUsuario/ModalExcluirUsuario.js, src/pages/Perfil/Perfil.js, src/pages/PerfilPaciente/PerfilPaciente.js, src/services/ManagerService/managerService.js, src/services/RequesterService/requesterService.js
Mudei a função no requester e manager para quando for excluir a conta do usuário excluir a tabela endereço, e como está em cascade o usuário é consequentemente apagado. Também adicionei um redirecionamento para o caso de a secretária excluir o próprio perfil.
=> Ao deletar o usuário apagar seu endereço Perfil Paciente Web, Perfil Web e Perfil App

package.json, src/pages/CriacaoFormulario/CriacaoFormulario.js, src/pages/CriacaoFormulario/Styles.js, src/services/ManagerService/managerService.js, src/styles/Select/Select.js, yarn.lock
Foi implementado títulos e um texto de instrução para os inputs da pagina criação formulário. Também foi realizada a lógica de campos nulos para os inputs e a pergunta.
=> Titulo, campos nulos e texto Criação de formulário

src/pages/ListaFormularios/ListaFormularios.js, src/pages/ListaFormularios/Styles.js
Lógica para renderizar 3 botões ou apenas 1 de acordo com o tipo de usuário e responsividade e estilização da página
=> Diferenciar usuários e estilização Lista Formularios

src/components/ModalAgendamento/ModalAgendamento.js, src/pages/Agendamentos/Agendamentos.js, src/pages/ListaUsuarios/ListaUsuarios.js, src/pages/ListaUsuarios/Styles.js, src/utils/tratamentoErros.js
Lógica para que os filtros agissem simultaneamente, lógica para não renderizar o filtro de data quando o médico selecionasse para filtrar por secretárias e estilização da página. Adição filtro "filtrar por codigo ou nome" e lógica para ele mudar de cor assim como a barra de pesquisa caso selecionar pra filtrar por código.
=> Filtro por código e simultaneamente lista de usuários

src/pages/Agendamentos/Agendamentos.js, src/pages/Agendamentos/Styles.js, src/pages/ListaUsuarios/Styles.js
Adicionamos o select por consultório, tornamos todos os presentes simultâneos, tratamos a responsividade da página e alteramos a borda do select de data para azul bem como o input caso se selecione filtrar por data. Mudamos o style da página de usuários para o codigo não quebrar.
=> Filtrar Agendamentos pelo Consultório e responsividade página agendamentos

src/components/ModalAgendamento/ModalAgendamento.js, src/pages/Agendamentos/Agendamentos.js, src/pages/AreaReceitas/AreaReceitas.js, src/pages/AreaReceitas/Styles.js, src/pages/ListaUsuarios/ListaUsuarios.js, src/pages/ListaUsuarios/Styles.js, src/utils/tratamentoErros.js, src/variaveis.js, yarn.lock
Criação da página Área de Receitas baseada na página Lista de Usuários. 
Foi necessário uma ordenação por data mais recente e também uma conversão do formato de data, de ISO para "short-date", criada na função "FormatarDataShort", para visualização do usuário. 
Havia uma função que ordenava as datas de mais antiga para mais recente, otimizei ela e criei uma copia para ordenar também de mais recente para mais antiga, que era o necessário nessa ordenação. Ambas as funções estão funcionais, porém estão no arquivo tratamento de erros, o que talvez não seja o ideal.
=> Área de Receitas

src/pages/ListaUsuarios/ListaUsuarios.js, src/pages/ListaUsuarios/Styles.js
Lógica para ordenar alfabeticamente os usuários caso esteja selecionado pra filtrar por todas as datas e por ordem decrescente de ultima visita caso queira filtrar por ultima visita. Responsividade selects e loader no centro da página
=>  Lógica ordenar por data ou alfabeticamente e css

src/components/ModalAdicionarCodigo/ModalAdicionarCodigo.js, src/components/ModalConsultaMarcada/ModalConsultaMarcada.js, src/components/ModalConsultaMarcada/Styles.js, src/components/ModalFormulario/Styles.js, src/pages/Agendamentos/Agendamentos.js, src/pages/FormularioEspecifico/FormularioEspecifico.js, src/pages/PerfilPaciente/PerfilPaciente.js
Alterações nos modais.
A maior dificuldade foi em relação ao RespostaFormulário. Já que ele está funcionando de forma dinâmica, a estilização é mais restrita. O fato de a quantidade de perguntas ser imprevisivel  dificulta a estilização fina, porque para que isso aconteça deve-se declará-la na variável "uiSchema" de maneira semelhante ao formato que se encontra o objeto.  
Uma provável forma de fazer isso seria desestruturando o objeto e adicionando uma tag para possibilitar a estilização ou, nesse caso, alterar o input para textarea. Por enquanto, o custo-benefício não se justifica ( também não sei se funcionaria ).
=> Alterações Modal Consulta Marcada, Editar Código e Resposta Formulário

src/components/ModalExcluirReceita/ModalExcluirReceita.js, src/components/ModalExcluirReceita/Styles.js, src/components/ModalExcluirReceita/index.js, src/pages/AreaReceitas/AreaReceitas.js, src/services/ManagerService/managerService.js, src/services/RequesterService/requesterService.js, src/styles/Button/Button.js
Criação de um modal para deletar a receita em questão
=> Deletar Receita Área de Receita Funcional

src/components/ModalAgendamentoEspecifico/ModalAgendamentoEspecifico.js, src/components/ModalAgendamentoEspecifico/Styles.js, src/components/ModalConsultaMarcada/ModalConsultaMarcada.js, src/components/ModalEditarAgendamentoEspecifico/ModalEditarAgendamentoEspecifico.js, src/components/ModalEditarAgendamentoEspecifico/Styles.js, src/pages/Agendamentos/Agendamentos.js
Colocar titulos nos inputs e responsividade dos titulos
Responsividade dos modais Editar consulta e agendamento específico
Implementação tooltip nos tipos e consultório
adição de scroll no nome paciente dos modais
=> Tooltip, Responsividade, Titulos, Modais

src/pages/AlterarSenhaComEmail/AlterarSenhaComEmail.js, src/pages/AlterarSenhaComEmail/Styles.js, src/pages/AlterarSenhaEsquecida/AlterarSenhaEsquecida.js, src/pages/AlterarSenhaEsquecida/Styles.js, src/pages/Login/Login.js, src/services/ManagerService/managerService.js
Foi criado uma pagina para recuperação de senha. Nela contém tratamento de erro, além de verificar se o e-mail escrito existe no banco de dados.
=> Esqueceu a senha web

src/pages/PerfilPaciente/PerfilPaciente.js, src/pages/PerfilPaciente/Styles.js
Modal de formulário não abrindo para secretários
=> Visualizar respostas secretária perfil paciente

src/components/ConversaAberta/ConversaAberta.js, src/components/HomeSecretaria/HomeSecretaria.js, src/pages/Chat/Chat.js, src/pages/ListaFormularios/ListaFormularios.js, src/pages/ListaFormularios/Styles.js, src/styles/Button/Button.js
Alterar responsividade do botão de cadastrar paciente, que estava quebrando. Criar função para possibilitar o médico mandar mensagem no chat em qualquer horário, mesmo após o horário comercial, arrumar o filtro de formulários por nível de urgência na página lista Formulários
=> Alterações Chat, Home, Lista Formulários

src/components/BarraLateralChat/BarraLateralChat.js, src/components/ConversaAberta/ConversaAberta.js, src/components/ConversaAberta/Styles.js, src/services/ManagerService/managerService.js, src/services/RequesterService/requesterService.js
Chats do tipo exame têm 3 funções adicionais: envio de um formulário de Actigrafia, confirmação do pagamento do exame e encerramento do chat.
=> Chat Exames Web

src/components/ModalAdicionarCodigo/ModalAdicionarCodigo.js, src/components/ModalEnvioFormulario/ModalEnvioFormulario.js, src/pages/CriacaoReceitas/CriacaoReceitas.js, src/pages/ListaFormularios/ListaFormularios.js, src/pages/ListaUsuarios/ListaUsuarios.js
*Página de Receita, ao criar uma receita, o loader NÃO carrega mais infinitamente;
*Página de Formulários, o modal para enviar o formulário se destrói quando fechado; e, quando enviar o fomulário para um paciente,  o loader NÃO carrega mais infinitamente e o modal se fecha sozinho sem recarregar a página;
*Página de Lista de Usuários, o modal para editar o código do paciente, ao ser fechado, não recarrega a Lista de Usuários.
=> Loader e correções Criar Receita, Modal de Envio e Modal Editar Codigo

.gitignore, package.json, src/components/ConversaAberta/ConversaAberta.js, src/components/ModalAgendamento/ModalAgendamento.js, src/components/ModalAgendamentoEspecifico/ModalAgendamentoEspecifico.js, src/components/ModalConsultaMarcada/ModalConsultaMarcada.js, src/components/ModalEditarAgendamentoEspecifico/ModalEditarAgendamentoEspecifico.js, src/pages/Agendamentos/Agendamentos.js, src/pages/AreaReceitas/AreaReceitas.js, src/pages/ListaUsuarios/ListaUsuarios.js, src/utils/formatarData.js, yarn.lock
. Foi corrigido o acréscimo de 3 horas no atributo "data_hora" das
consultas.
. Para a correção e formatação das datas foi utilizado a lib
"data-fns-tz".
. Algumas variáveis que não estavam em uso foram excluídas.
. A lib "moment" foi excluída e suas funcionalidades substituídas pela
"data-fns-tz".
. No ".gitignore" foi adicionado o arquivo ".editorconfig" de cofiguração
local.
=> fix: problema com datas em algumas páginas

src/pages/AreaReceitas/AreaReceitas.js, src/pages/AreaReceitas/Styles.js, src/pages/UploadReceita/Styles.js, src/pages/UploadReceita/UploadReceita.js, src/pages/UploadReceita/index.js, src/routes.js
- Criação da página de upload
- Adicionado biblioteca Antd para realizar o upload de receitas
- O select “Nome do Paciente” está puxando todos os pacientes cadastrados
- Adicionado background green para botões não funcionais 
- Estilização dos inputs.
=> Página Estática Upload Receita

src/components/ConversaAberta/ConversaAberta.js
Adicionado o menu com mensagens automáticas.
=> Chat Web FAQ Normal

src/services/ManagerService/managerService.js
O token é armazenado no frontend.
=> Autenticação para rotas de back

src/pages/EdicaoSobreMim/EdicaoSobreMim.js, src/pages/EdicaoSobreMim/Styles.js, src/services/RequesterService/requesterService.js
=> fix problemas de responsividade, feat redirecionam

src/components/ConversaAberta/ConversaAberta.js, src/components/Mensagem/Mensagem.js, src/services/ManagerService/managerService.js
- Instruções para realização do exame de actigrafia mandadas ao pressionar botão confirmar pagamento
=> Enviar instruções pelo chat

src/components/ModalEnvioFormulario/ModalEnvioFormulario.js, src/components/ModalEnvioFormulario/Styles.js, src/pages/CriacaoReceitas/CriacaoReceitas.js, src/pages/CriacaoReceitas/Styles.js, src/styles/Select Antd/SelectAntd.js, src/styles/Select Antd/index.js
- Selects corrigidos, sendo impletados em ordem alfabética e com pesquisa por inicial.
=> Corrigindo selects

src/components/ModalEditarConsulta/ModalEditarConsulta.js, src/components/ModalEditarConsulta/Styles.js, src/components/ModalEditarExame/ModalEditarExame.js, src/components/ModalEditarExame/Styles.js
Todos os itens da tarefa abordados
=> Finalizar ediçãode agendamentos por modal

src/components/HomeMedico/HomeMedico.js, src/components/HomeMedico/Styles.js
- Retirada do botão de avaliação app.
- Correção na responsividade.
=> Finalizar Home Médico

package.json, src/pages/CriacaoReceitas/CriacaoReceitas.js, src/pages/UploadReceita/UploadReceita.js, src/services/ManagerService/managerService.js, yarn.lock
=> Finalização de Assinatura

src/pages/CriacaoReceitas/CriacaoReceitas.js, src/pages/UploadReceita/Styles.js, src/pages/UploadReceita/UploadReceita.js, src/services/ManagerService/managerService.js, src/services/RequesterService/requesterService.js, src/services/api.js
=> Pdf doctor bugs
